# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Federation.create(id:1, name:"Federação das Empresas Juniores do Distrito Federal", abbreviation:"Concentro")
Role.create(id:1, name:"Diretor", organogram_id:1)
Role.create(id:2, name:"Coordenador", organogram_id:1)
Role.create(id:3, name:"Assessor", organogram_id:1)
Perfomance.create(id: 1, name: "Avaliação de Desempenho - Diretor", federations_id: 1, role_id: 1)
Perfomance.create(id: 2, name: "Avaliação de Desempenho - Coordenador", federations_id: 1, role_id: 2)
Perfomance.create(id: 3, name: "Avaliação de Desempenho - Assessor", federations_id: 1, role_id: 3)
Dimension.create(id:1, name:"Responsabilidade - Diretor", description:"Capacidade de honrar os compromissos assumidos e de cumprir prazos.", perfomance_id:1)
Dimension.create(id:2, name:"Proatividade - Diretor", description:"Considere a disposição do membro para realizar uma atividade sem ser requisitado.", perfomance_id:1)
Dimension.create(id:3, name:"Qualidade das Entregas - Diretor", description:"Considere a execução de trabalhos de maneira organizada e criteriosa, atendendo aos procedimentos e padrões adequados.", perfomance_id:1)
Dimension.create(id:4, name:"Utilização de Ferramentas - Diretor", description:"Utilização eficiente das ferramentas é o uso que não traz prejuízos à execução das atividades.", perfomance_id:1)
Dimension.create(id:5, name:"Trabalho em Equipe - Diretor", description:"Capacidade e disposição para trabalhar com grupos de pessoas que detenham conhecimentos e opiniões diversas, buscando a sinergia e a otimização dos resultados.", perfomance_id:1)
Dimension.create(id:6, name:"Feedback - Diretor", description:"Capacidade de transmitir feedbacks contextualizados e pertinentes, além de adotar postura receptiva para recebê-los.", perfomance_id:1)
Dimension.create(id:7, name:"Alinhamento - Diretor", description:"Considere alinhamento como ter (os objetivos individuais) as metas mensais coerentes aos objetivos estratégicos da Concentro.", perfomance_id:1)
Dimension.create(id:8, name:"Pertencimento - Diretor", description:"Considere se o membro apresenta comportamentos que possam indicar que ele se sente parte da Equipe.(Considere engajado como o comportamento que ele demonstra diante a iniciativa)", perfomance_id:1)
Dimension.create(id:9, name:"Responsabilidade - Coordenador", description:"Capacidade de honrar os compromissos assumidos e de cumprir prazos.", perfomance_id:2)
Dimension.create(id:10, name:"Proatividade - Coordenador", description:"Considere a disposição do membro para realizar uma atividade sem ser requisitado.", perfomance_id:2)
Dimension.create(id:11, name:"Qualidade das Entregas - Coordenador", description:"Considere a execução de trabalhos de maneira organizada e criteriosa, atendendo aos procedimentos e padrões adequados.", perfomance_id:2)
Dimension.create(id:12, name:"Utilização de Ferramentas - Coordenador", description:"Utilização eficiente das ferramentas é o uso que não traz prejuízos à execução das atividades.", perfomance_id:2)
Dimension.create(id:13, name:"Trabalho em Equipe - Coordenador", description:"Capacidade e disposição para trabalhar com grupos de pessoas que detenham conhecimentos e opiniões diversas, buscando a sinergia e a otimização dos resultados.", perfomance_id:2)
Dimension.create(id:14, name:"Feedback - Coordenador", description:"Capacidade de transmitir feedbacks contextualizados e pertinentes, além de adotar postura receptiva para recebê-los.", perfomance_id:2)
Dimension.create(id:15, name:"Alinhamento - Coordenador", description:"Considere alinhamento como ter (os objetivos individuais) as metas mensais coerentes aos objetivos estratégicos da Concentro.", perfomance_id:2)
Dimension.create(id:16, name:"Pertencimento - Coordenador", description:"Considere se o membro apresenta comportamentos que possam indicar que ele se sente parte da Equipe.(Considere engajado como o comportamento que ele demonstra diante a iniciativa)",  perfomance_id:2)
Dimension.create(id:17, name:"Responsabilidade - Assessor", description:"Capacidade de honrar os compromissos assumidos e de cumprir prazos.", perfomance_id:3)
Dimension.create(id:18, name:"Proatividade - Assessor", description:"Considere a disposição do membro para realizar uma atividade sem ser requisitado.",  perfomance_id:3)
Dimension.create(id:19, name:"Qualidade das Entregas - Assessor", description:"Considere a execução de trabalhos de maneira organizada e criteriosa, atendendo aos procedimentos e padrões adequados.",  perfomance_id:3)
Dimension.create(id:20, name:"Utilização de Ferramentas - Assessor", description:"Utilização eficiente das ferramentas é o uso que não traz prejuízos à execução das atividades.",  perfomance_id:3)
Dimension.create(id:21, name:"Trabalho em Equipe - Assessor", description:"Capacidade e disposição para trabalhar com grupos de pessoas que detenham conhecimentos e opiniões diversas, buscando a sinergia e a otimização dos resultados.",  perfomance_id:3)
Dimension.create(id:22, name:"Feedback - Assessor", description:"Capacidade de transmitir feedbacks contextualizados e pertinentes, além de adotar postura receptiva para recebê-los.",  perfomance_id:3)
Dimension.create(id:23, name:"Alinhamento - Assessor", description:"Considere alinhamento como ter (os objetivos individuais) as metas mensais coerentes aos objetivos estratégicos da Concentro.", perfomance_id:3)
Dimension.create(id:24, name:"Pertencimento - Assessor", description:"Considere se o membro apresenta comportamentos que possam indicar que ele se sente parte da Equipe.(Considere engajado como o comportamento que ele demonstra diante a iniciativa)", perfomance_id:3)
Question.create(id:1, question:"O membro cumpre os prazos previamente estabelecidos.", dimension_id:1)
Question.create(id:2, question:"O membro assume responsabilidade pelos resultados de suas atividades, sejam eles positivos ou negativos.", dimension_id:1)
Question.create(id:3, question:"O membro comparece às atividades da Concentro relacionadas à sua área.", dimension_id:1)
Question.create(id:4, question:"O membro comparece às Reuniões Gerais", dimension_id:1)
Question.create(id:5, question:"Caso o membro não consiga cumprir um prazo, comunica a equipe com antecedência.", dimension_id:1)
Question.create(id:6, question:"O membro reporta com antecedência atrasos ou ausências nas reuniões e outras atividades", dimension_id:1)
Question.create(id:7, question:"O membro se oferece para realizar tarefas necessárias para o bom andamento das atividades da equipe.", dimension_id:2)
Question.create(id:8, question:"O membro busca alternativas para problemas na coordenadoria sem esperar passivamente pelas soluções.", dimension_id:2)
Question.create(id:9, question:"O membro busca previamente trazer referências para as discussões propostas para as reuniões, quando necessário.", dimension_id:2)
Question.create(id:10, question:"A qualidade das entregas do membro é  influenciada positivamente pelo conhecimento técnico sobre a área ", dimension_id:3)
Question.create(id:11, question:" As entregas feitas pelo membro conseguem atingir os objetivos esperados pela equipe.", dimension_id:3)
Question.create(id:12, question:"O número de atividades assumidas pelo membro fora da Concentro não prejudica a qualidade de suas entregas da federação", dimension_id:3)
Question.create(id:13, question:"O membro responde os e-mails com frequencia de forma a facilitar o trabalho na Concentro", dimension_id:4)
Question.create(id:14, question:"O membro atualiza semanalmente o Trello de forma a facilitar o trabalho na Concentro", dimension_id:4)
Question.create(id:15, question:"O membro atualiza semanalmente a agenda de forma a facitar o trabalho na Concentro", dimension_id:4)
Question.create(id:16, question:"O membro atualiza o drive conforme a finalização dos processos e projetos", dimension_id:4)
Question.create(id:17, question:"A comunicação com o membro pelas ferramentas de gestão é efetiva", dimension_id:4)
Question.create(id:18, question:"O membro contribui para o resultado da equipe", dimension_id:5)
Question.create(id:19, question:"O membro preza pelo bom relacioquestionnto da equipe.", dimension_id:5)
Question.create(id:20, question:"O membro auxilia a equipe quando esta necessita de ajuda.", dimension_id:5)
Question.create(id:21, question:"O membro demonstra respeito às opiniões e aos posicioquestionntos da equipe.", dimension_id:5)	
Question.create(id:22, question:"O membro fornece feedbacks a equipe para melhoraria das   atividades em conjunto.", dimension_id:6)
Question.create(id:23, question:"O membro utiliza os feedbacks recebidos para melhorar seu desempenho.", dimension_id:6)
Question.create(id:24, question:"O membro tem uma postura receptiva ao receber um feedback", dimension_id:6)
Question.create(id:25, question:"O coordenador relaciona as atividades dos assessores a estratégia da Concentro no momento de delega-las", dimension_id:7)
Question.create(id:26, question:"O membro é capaz de explicar a contribuição da sua meta mensal  para os objetivos estratégicos da Concentro.", dimension_id:7)
Question.create(id:27, question:"O membro busca novos meios para atingir sua meta mensal", dimension_id:7)
Question.create(id:28, question:"O membro propõe ideias e sugestões alinhadas à estratégia e à dinâmica de trabalho da Concentro.", dimension_id:7)
Question.create(id:29, question:"O membro se mostra engajado com  as iniciativas da Concentro (integrações, Sábado Júnior, SAC Oficinas...).", dimension_id:8)
Question.create(id:30, question:"O membro comparace às iniciativas da Concentro (integrações, Sábado Júnior, SAC Oficinas...)", dimension_id:8)
Question.create(id:31, question:"O membro se dispõe a realizar atividades que ajudem outras áreas, por exemplo: ser staff das iniciativas da Concentro", dimension_id:8)
Question.create(id:32, question:"O membro se esforça para ter um bom relacioquestionnto com a equipe Concentro", dimension_id:8)
Question.create(id:33, question:"O membro se esforça para ter um bom relacioquestionnto com os membros da coordenadoria", dimension_id:8)
Question.create(id:34, question:"O membro cumpre os prazos previamente estabelecidos.", dimension_id:9)
Question.create(id:35, question:"O membro assume responsabilidade pelos resultados de suas atividades, sejam eles positivos ou negativos.", dimension_id:9)
Question.create(id:36, question:"O membro comparece às atividades da Concentro relacionadas à sua área.", dimension_id:9)
Question.create(id:37, question:"O membro comparece às Reuniões Gerais", dimension_id:9)
Question.create(id:38, question:"Caso o membro não consiga cumprir um prazo, comunica a equipe com antecedência.", dimension_id:9)
Question.create(id:39, question:"O membro reporta com antecedência atrasos ou ausências nas reuniões e outras atividades", dimension_id:9)
Question.create(id:40, question:"O membro se oferece para realizar tarefas necessárias para o bom andamento das atividades da equipe.", dimension_id:10)
Question.create(id:41, question:"O membro busca alternativas para problemas na coordenadoria sem esperar passivamente pelas soluções.", dimension_id:10)
Question.create(id:42, question:"O membro busca previamente trazer referências para as discussões propostas para as reuniões, quando necessário.", dimension_id:10)
Question.create(id:43, question:"A qualidade das entregas do membro é  influenciada positivamente pelo conhecimento técnico sobre a área", dimension_id:11)
Question.create(id:44, question:"As entregas feitas pelo membro conseguem atingir os objetivos esperados pela equipe.", dimension_id:11)
Question.create(id:45, question:"O membro consegue fazer uso da gestão do tempo, independente das suas atividades alheias à Concentro, de forma a entregar suas tarefas com qualidade.", dimension_id:11)
Question.create(id:46, question:"O membro responde os e-mails com frequencia de forma a facilitar o trabalho na Concentro", dimension_id:12)
Question.create(id:47, question:"O membro atualiza semanalmente o Trello de forma a facilitar o trabalho na Concentro", dimension_id:12)
Question.create(id:48, question:"O membro atualiza semanalmente a agenda de forma a facitar o trabalho na Concentro", dimension_id:12)
Question.create(id:49, question:"O membro atualiza o drive conforme a finalização dos processos e projetos", dimension_id:12)
Question.create(id:50, question:"A comunicação com o membro pelas ferramentas de gestão é efetiva", dimension_id:12)
Question.create(id:51, question:"O membro contribui para o resultado da equipe", dimension_id:13)
Question.create(id:52, question:"O membro preza pelo bom relacionamento da equipe.", dimension_id:13)
Question.create(id:53, question:"O membro auxilia a equipe quando esta necessita de ajuda.", dimension_id:13)
Question.create(id:54, question:" O membro demonstra respeito às opiniões e aos posicionamentos da equipe.", dimension_id:13)
Question.create(id:55, question:"O membro fornece feedbacks a equipe para melhoraria das atividades em conjunto.", dimension_id:14)
Question.create(id:56, question:"O membro utiliza os feedbacks recebidos para melhorar seu desempenho.", dimension_id:14)
Question.create(id:57, question:"O membro tem uma postura receptiva ao receber um feedback", dimension_id:14)
Question.create(id:58, question:"O coordenador relaciona as atividades dos assessores a estratégia da Concentro no momento de delega-las", dimension_id:15)
Question.create(id:59, question:"O membro é capaz de explicar a contribuição da sua meta mensal  para os objetivos estratégicos da Concentro.", dimension_id:15)
Question.create(id:60, question:"O membro busca novos meios para atingir sua meta mensal.", dimension_id:15)
Question.create(id:61, question:"O membro propõe ideias e sugestões alinhadas à estratégia e à dinâmica de trabalho da Concentro.", dimension_id:15)
Question.create(id:62, question:"O membro se mostra engajado com  as iniciativas da Concentro (integrações, Sábado Júnior, SAC Oficinas...).", dimension_id:16)
Question.create(id:63, question:"O membro comparace às iniciativas da Concentro (integrações, Sábado Júnior, SAC Oficinas...).", dimension_id:16)
Question.create(id:64, question:"O membro se dispõe a realizar atividades que ajudem outras áreas, por exemplo: ser staff das iniciativas da Concentro", dimension_id:16)
Question.create(id:65, question:"O membro se esforça para ter um bom relacionamento com a equipe Concentro", dimension_id:16)
Question.create(id:66, question:" o membro se esforça para ter um bom relacionamento com os membros da coordenadoria", dimension_id:16)
User.create!({:id=>29, :email=>"lucascosta@concentro.org.br",:password => "TsdkZm6G", :password_confirmation => "TsdkZm6G", :role_id=> 1})	
User.create!({:id=>9, :email=>"caiovivan@concentro.org.br",:password => "df9649EL", :password_confirmation => "df9649EL", :role_id=> 2})
User.create!({:id=>21, :email=>"helenagalvani@concentro.org.br",:password => "munzNDU2", :password_confirmation => "munzNDU2", :role_id=> 3})		
User.create!({:id=>35, :email=>"luizfrancois@concentro.org.br",:password => "2SnV5Zk6", :password_confirmation => "2SnV5Zk6", :role_id=> 3})
User.create!({:id=>49, :email=>"tuliomoraes@concentro.org.br",:password => "uKwCbUZX", :password_confirmation => "uKwCbUZX", :role_id=> 3})
User.create!({:id=>23, :email=>"henriquetagliari@concentro.org.br",:password => "AGHRguc9", :password_confirmation => "AGHRguc9", :role_id=> 1})	
User.create!({:id=>36, :email=>"marcelorodrigues@concentro.org.br",:password => "5H8apaR9", :password_confirmation => "5H8apaR9", :role_id=> 2})
User.create!({:id=>7, :email=>"anaoyafuco@concentro.org.br",:password => "ejbmPXh2", :password_confirmation => "ejbmPXh2", :role_id=> 3})
User.create!({:id=>17, :email=>"gabrielaidar@concentro.org.br",:password => "apB2QwEr", :password_confirmation => "apB2QwEr", :role_id=> 3})
User.create!({:id=>39, :email=>"mhamassaki@concentro.org.br",:password => "dJLPnGzA", :password_confirmation => "dJLPnGzA", :role_id=> 3})		
User.create!({:id=>8, :email=>"andregiampaolo@concentro.org.br",:password => "d7GmLzNW", :password_confirmation => "d7GmLzNW", :role_id=> 2})
User.create!({:id=>30, :email=>"lucasmafra@concentro.org.br",:password => "wafWhC59", :password_confirmation => "wafWhC59", :role_id=> 3})		 		
User.create!({:id=>41, :email=>"otavioandrade@concentro.org.br",:password => "zmTmHMjp", :password_confirmation => "zmTmHMjp", :role_id=> 1})
User.create!({:id=>4, :email=>"anafonseca@concentro.org.br",:password => "mdhAeL4E", :password_confirmation => "mdhAeL4E", :role_id=> 2})
User.create!({:id=>1, :email=>"adalbertosampaio@concentro.org.br",:password => "gabBgqRq", :password_confirmation => "gabBgqRq", :role_id=> 3})
User.create!({:id=>42, :email=>"raphaelecaixeta@concentro.org.br",:password => "Cdmqvdkr", :password_confirmation => "Cdmqvdkr", :role_id=> 3})
User.create!({:id=>43, :email=>"rebecagarcia@concentro.org.br",:password => "h8bjdD3Y", :password_confirmation => "h8bjdD3Y", :role_id=> 3})
User.create!({:id=>27, :email=>"joaoalonso@concentro.org.br",:password => "eH69wR96", :password_confirmation => "eH69wR96", :role_id=> 2})
User.create!({:id=>10, :email=>"carolinaviegas@concentro.org.br",:password => "7WJn5GVd", :password_confirmation => "7WJn5GVd", :role_id=> 3})
User.create!({:id=>16, :email=>"fernandacostandrade@concentro.org.br",:password => "4vJJfW2W", :password_confirmation => "4vJJfW2W", :role_id=> 3})
User.create!({:id=>12, :email=>"eduardogonzalez@concentro.org.br",:password => "wMXAfAMh", :password_confirmation => "wMXAfAMh", :role_id=> 3})
User.create!({:id=>46, :email=>"thainalima@concentro.org.br",:password => "bNxgsAfe", :password_confirmation => "bNxgsAfe", :role_id=> 3})		
User.create!({:id=>13, :email=>"dante.akira@concretaconsultoria.com.br",:password => "LmZRrrdd", :password_confirmation => "LmZRrrdd", :role_id=> 3})
User.create!({:id=>14, :email=>"emilly.ramos@factoagencia.com.br",:password => "SmvW44LF", :password_confirmation => "SmvW44LF", :role_id=> 3})
User.create!({:id=>15, :email=>"paivacarolyna@gmail.com",:password => "Gq2fUeBV", :password_confirmation => "Gq2fUeBV", :role_id=> 3})
User.create!({:id=>25, :email=>"irezendesilva@concentro.org.br",:password => "GK5Pw6np", :password_confirmation => "GK5Pw6np", :role_id=> 3})
User.create!({:id=>32, :email=>"luisamarini@concentro.org.br",:password => "FUzesJqP", :password_confirmation => "FUzesJqP", :role_id=> 1})
User.create!({:id=>38, :email=>"marioguedes@concentro.org.br",:password => "Dqwe536n", :password_confirmation => "Dqwe536n", :role_id=> 2})		
User.create!({:id=>11, :email=>"clarissaalho@concentro.org.br",:password => "DFy656GH", :password_confirmation => "DFy656GH", :role_id=> 3})
User.create!({:id=>19, :email=>"gabriellobo@concentro.org.br",:password => "V2vCzC4a", :password_confirmation => "V2vCzC4a", :role_id=> 3})
User.create!({:id=>20, :email=>"gabrielperucchi@concentro.org.br",:password => "VJEArK8P", :password_confirmation => "VJEArK8P", :role_id=> 3})
User.create!({:id=>48, :email=>"thayannesales@concentro.org.br",:password => "v4sL5yRF", :password_confirmation => "v4sL5yRF", :role_id=> 3})
User.create!({:id=>5, :email=>"anagabriela@concentro.org.br",:password => "VcEQf7kA", :password_confirmation => "VcEQf7kA", :role_id=> 2})
User.create!({:id=>31, :email=>"lucasrodrigues@concentro.org.br",:password => "Ufzm5VzG", :password_confirmation => "Ufzm5VzG", :role_id=> 3})
User.create!({:id=>37, :email=>"marinatorres@concentro.org.br",:password => "8hkNAhHK", :password_confirmation => "8hkNAhHK", :role_id=> 3})
User.create!({:id=>40, :email=>"monicamaranhao@concentro.org.br",:password => "c5aTUbgU", :password_confirmation => "c5aTUbgU", :role_id=> 3})		
User.create!({:id=>2, :email=>"alannogales@concentro.org.br",:password => "REuXAjuq", :password_confirmation => "REuXAjuq", :role_id=> 1})	
User.create!({:id=>34, :email=>"luizedmiranda@concentro.org.br",:password => "bsybfXL5", :password_confirmation => "bsybfXL5", :role_id=> 2})	
User.create!({:id=>50, :email=>"victorho@concentro.org.br",:password => "NNjRk7Xb", :password_confirmation => "NNjRk7Xb", :role_id=> 3})		
User.create!({:id=>28, :email=>"kiepherkennedy@concentro.org.br",:password => "pQda9B58", :password_confirmation => "pQda9B58", :role_id=> 2})
User.create!({:id=>6, :email=>"analuizaprado@concentro.org.br",:password => "NAD9EwKp", :password_confirmation => "NAD9EwKp", :role_id=> 3})
User.create!({:id=>24, :email=>"igorcaldeira@concentro.org.br",:password => "DN5RSHGt", :password_confirmation => "DN5RSHGt", :role_id=> 3})
User.create!({:id=>26, :email=>"isabelbarcelos@concentro.org.br",:password => "BtEUUpre", :password_confirmation => "BtEUUpre", :role_id=> 3})
User.create!({:id=>45, :email=>"tayanenunes@concentro.org.br",:password => "w8zjvSup", :password_confirmation => "w8zjvSup", :role_id=> 3})				
User.create!({:id=>51, :email=>"victormedeiros@concentro.org.br",:password => "TuPkhxQ2", :password_confirmation => "TuPkhxQ2", :role_id=> 1})
User.create!({:id=>33, :email=>"luizamonteiro@concentro.org.br",:password => "jqCRZ4HU", :password_confirmation => "jqCRZ4HU", :role_id=> 2})
User.create!({:id=>3, :email=>"anabarbosa@concentro.org.br",:password => "7nY5vJYx", :password_confirmation => "7nY5vJYx", :role_id=> 3})
User.create!({:id=>18, :email=>"gabrielavieira@concentro.org.br",:password => "GyG3a7hK", :password_confirmation => "GyG3a7hK", :role_id=> 3})
User.create!({:id=>22, :email=>"henriqueneres@concentro.org.br",:password => "W6mYRvVz", :password_confirmation => "W6mYRvVz", :role_id=> 3})
User.create!({:id=>44, :email=>"sathyagimenes@concentro.org.br",:password => "tcmU4VsS", :password_confirmation => "tcmU4VsS", :role_id=> 3})
User.create!({:id=>47, :email=>"thalesvinkler@concentro.org.br",:password => "12345678", :password_confirmation => "12345678", :role_id=> 1})